name: archer
version: 0.0.1
description: QuickCheck inspired testing for Dart
authors:
  - Yehor Lvivski <lvivski@gmail.com>
  - Denis Yermakov
  - Serhiy Oplakanets
homepage: http://github.com/lvivski/archer